apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: bitnami/postgresql:latest
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        command: ["/bin/sh", "-c"]
        args:
          - |
            until pg_isready -h postgresql -U $PGUSER -d $PGDATABASE; do
              sleep 2
              echo "Waiting for PostgreSQL..."
            done
            
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "
              CREATE TABLE IF NOT EXISTS users (
                id BIGSERIAL PRIMARY KEY,
                username VARCHAR(255) NOT NULL UNIQUE,
                firstname VARCHAR(255) NOT NULL,
                lastname VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                phone VARCHAR(50) NOT NULL
              );"
            
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "
              CREATE TABLE IF NOT EXISTS auth_users (
                  id BIGSERIAL PRIMARY KEY,
                  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  username VARCHAR(255) UNIQUE NOT NULL,
                  password_hash VARCHAR(255) NOT NULL
              );"
            
            echo "Database structure:"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "\dt"
            
            echo "Table details:"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "\d+ users"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "\d+ auth_users"
            
            echo "Migration completed successfully!"
      restartPolicy: Never
  backoffLimit: 2