apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: bitnami/postgresql:latest
        envFrom:
        - secretRef:
            name: db-secret
        command: ["/bin/sh", "-c"]
        args:
          - |
            export PGPASSWORD=$(echo "$POSTGRES_PASSWORD" | base64 -d)
            export PGUSER=$(echo "$POSTGRES_USER" | base64 -d)
            export PGDATABASE=$(echo "$POSTGRES_DB" | base64 -d)
            
            until pg_isready -h postgresql -U $PGUSER -d $PGDATABASE; do
              sleep 2
              echo "Waiting for PostgreSQL..."
            done
            
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "
              CREATE TABLE IF NOT EXISTS users (
                id BIGSERIAL PRIMARY KEY,
                username VARCHAR(255) NOT NULL UNIQUE,
                firstname VARCHAR(255) NOT NULL,
                lastname VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                phone VARCHAR(50) NOT NULL
              );"
            
            echo "Database structure:"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "\dt"
            
            echo "Table details:"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "\d+ users"
            
            echo "Sample data:"
            psql -h postgresql -U $PGUSER -d $PGDATABASE -c "SELECT * FROM users LIMIT 5;"
            
            echo "Migration completed successfully!"
      restartPolicy: Never
  backoffLimit: 2