app:
  image:
    repository: flowers-api
    tag: 1.0.0
    pullPolicy: IfNotPresent
  port: 80

db:
  host: postgresql
  name: users_db
  user: postgres
  password: postgres

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix
        - path: /user
          pathType: Prefix

config:
  appsettings: |-
    {
      "ConnectionStrings": {
        "DefaultConnection": "Host=postgresql;Port=5432;Database=users_db;Username=postgres;Password=postgres"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }