apiVersion: v1
kind: ConfigMap
metadata:
  name: flowers-config
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "DefaultConnection": "Host=postgresql;Port=5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }