apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowers-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: flowers-service
            port:
              number: 80
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: flowers-service
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: flowers-service
            port:
              number: 80
      - path: /metrics
        pathType: Exact
        backend:
          service:
            name: flowers-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flowers-service
            port:
              number: 80